# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FMDBDemo_swift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FMDBDemo_swift
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'FMDB'

end
