# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FMDBDemo_oc' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FMDBDemo_oc
  pod 'AFNetworking'
  pod 'FMDB'
  
end
